[tool.poetry]
name = "djangoboyz"
version = "0.1.0"
description = ""
authors = ["antani"]

[tool.poetry.dependencies]
python = "^3.11"
Django = "4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
