# Generated by Django 3.2.19 on 2023-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
